on:
  pull_request:
  push:
    branches:
      - main
name: release
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  release-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}

      # Format changelog, workaround for https://github.com/google-github-actions/release-please-action/issues/542
      # Taken from https://github.com/remarkablemark/release-please-extra-files-demo/blob/master/.github/workflows/release-please.yml
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ steps.release.outputs.pr }}
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}
          fetch-depth: 0
          ref: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

      - name: Configure Git user
        if: ${{ steps.release.outputs.pr }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git --no-pager show --name-only

      - name: Format CHANGELOG.md
        if: ${{ steps.release.outputs.pr }}
        run: npx oxfmt CHANGELOG.md .release-please-manifest.json

      - name: Commit
        if: ${{ steps.release.outputs.pr }}
        run: |
          git add CHANGELOG.md .release-please-manifest.json
          git commit -m 'chore: Format CHANGELOG.md' --no-verify

      - name: Push changes
        if: ${{ steps.release.outputs.pr }}
        uses: ad-m/github-push-action@4cc74773234f74829a8c21bc4d69dd4be9cfa599 # v1.1.0
        with:
          github_token: ${{ secrets.RELEASE_PR_TOKEN }}
          branch: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    needs: [release-pr]
    if: ${{ (github.event_name == 'pull_request' || needs.release-pr.outputs.release_created == 'true') && always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Submit to stores
        run: |
          pnpm wxt submit \
            ${{ github.event_name == 'pull_request' && '--dry-run' || '' }} \
            --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip

        #--chrome-zip .output/*-chrome.zip \
        #--edge-zip .output/{your-extension}-{version}-chrome.zip
        env:
          #CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          #CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          #CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          #CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: "@jabfox"
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
