name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
  test:
    name: Test (${{ matrix.target }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: test
            runs-on: ubuntu-latest
          - target: safari-build
            runs-on: macos-latest
    steps:
      - name: Setup build environment
        uses: ./.github/actions/setup-browser-extension
        with:
          submodules: true

      - name: Run tests
        if: ${{ matrix.target == 'test' }}
        run: pnpm test

      - name: Build Safari app
        if: ${{ matrix.target == 'safari-build' }}
        run: make safari
